### ISSUE TITLE
Feature Request List V5

### ISSUE THREAD

**Issue by TheTerrarian101** [SxClient/SxClient#11]
Hopefully this will makes things easier, anyways here's a list:

- HitTP/Grapple

- Anti-bot

- Change Air Speed (Doesn't mess with ground speed)

- Change Friction

- More bypasses

- Auto-Armor

- Scaffold

V2:

 - Auto-eat (Activates when u hold an edible item)

- Maybe an expect release date for next update?

- Fast eat

- Aimbot

- Hitbox

- Auto-Hit (Like killaura, activates when u hover over an enemy player)

V3:

- Auto-Sword (Activates when u tap/attack en enemy)[Or](When an enemy gets within range your sword is automatically selected)

- Blink

- Hold Packet(s)

- HiderESP

- Bypass jetpack

- No Web/Soulsand/Ice/Slimeblock

- ViewTP

- EnchantSpam

- Different types of auras

- No weather

- Fast Regen

- FPS Counter/Displayer

- No Void

- Twerk

- TapExplosion

- ChestSteal

V4:

- Murderer Finder (Useful for Murder Mystery)(When someone holds up their sword a nametag or ESP is placed on the person who held it)

- Bypass Immortality/Many hearts (Gives you a lot of hearts)

- CrouchTP

- RandomTP

V5

- Built-in auto-clicker (As fast/faster than killaura and is always tapping where u are hovering)

- Spammer

- TapSpam

**Comment by yoooooooagk** [comment]
Hi,  If anyone reads this, can u guys make a ghost feature? Like you gotta click in a corner after clicking in the feature and the text gun doesn't appear so u can survive SS.

**Comment by Seyz123** [comment]
Since Toolbox is no longer updated and it will certainly have a launcher, I close this issue.
