### ISSUE TITLE
What APK editor?

### ISSUE THREAD

**Issue by TwistedAsylumMC** [SxClient/SxClient#12]
Could you please leave a link to the APK editor you use for this project? I have tried many different applications and none of them have the options you provided in the readme, and none of them let me save a modified APK.

**Comment by Seyz123** [comment]
Hello,
For APK Editor, the app is no longer available on the Google Play Store.
Nevertheless, you can use this one :
http://www.mediafire.com/file/bsktdr7asf43leu/APK_Editor_Pro.ver.1.10.0.build.121.apk/file
You can also press the "Download latest APK" on the ReadMe to download the latest SxClient's build.

**Comment by TwistedAsylumMC** [comment]
Alright, thanks for the quick response
